apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: reviews  
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  namespace: reviews    
  labels:
    account: reviews
---